build GitHub plugin
Green-Software-Foundation/if-github-plugin pull request #1
Opened 2024-07-18 15:31 UTC by manushak

2024-07-19 13:22 UTC, narekhovhannisyan commented on README.md
> +- To calculate `clones`, the plugin uses [this](https://docs.github.com/en/rest/metrics/traffic) endpoint.
```suggestion
- To calculate `clones`, the plugin uses [traffic](https://docs.github.com/en/rest/metrics/traffic) endpoint.
```

2024-07-19 13:22 UTC, narekhovhannisyan commented on README.md
> +- To get `size` of the repository, the plugin uses [this](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository) endpoint.
```suggestion
- To get `size` of the repository, the plugin uses [get a repository](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository) endpoint.
```

2024-07-19 13:25 UTC, narekhovhannisyan commented on src/lib/github/api.ts
> +      return await axios.get(`https://api.github.com/orgs/${owner}`);
please setup base axios object 

```ts
const GithubAPI = axios.createInstance({ baseURL: https://api.github.com/' })
```

and reuse it in methods

```ts
const checkOwnerValidity = async (owner: string) => {
    try {
      return await GithubAPI.get(`orgs/${owner}`);
      } ...
```

2024-07-19 13:26 UTC, narekhovhannisyan commented on src/lib/github/api.ts
> +      return result?.data.clones;
you can use response interceptor to make accessing the response data quicker

2024-07-19 13:26 UTC, narekhovhannisyan commented on src/lib/github/index.ts
> +    kind: 'execute',
shouldn't we add input and output data to it?

2024-07-19 13:38 UTC, narekhovhannisyan commented on src/util/errors.ts
> +export const ERRORS = CUSTOM_ERRORS.reduce((acc, className) => {
We have to use if-core

2024-07-19 13:38 UTC, narekhovhannisyan requested changes
Please check the comment above

2024-07-23 09:47 UTC, jmcook1186 approved these changes
sgtm!

2024-07-23 10:19 UTC, narekhovhannisyan approved these changes

2024-07-23 10:20 UTC, narekhovhannisyan commented
@jmcook1186 I think we have to incapsulate validation into if-core too.

2024-07-24 09:50 UTC, merged